export default [
  {
    postNo: 1,
    title: '게시글1',
    id: 'userName_1',
    price: '10000',
    salesPrice: '5000',
    salesYn: 'Y',
    salesPct: '50 %',
    tags: 'TEST',
    originName: 'aasaasdasdasd',

    getTags: () => ['test'],
    getPrice: () => '10000',
    getSalesPrice: () => '5000',
    isSales: () => true,
  },
  {
    postNo: 1,
    title: '게시글1',
    id: 'userName_1',
    price: '10000',
    salesPrice: '5000',
    salesYn: 'Y',
    salesPct: '50 %',
    tags: 'TEST',
    originName: 'aasaasdasdasd',

    getTags: () => ['test'],
    getPrice: () => '10000',
    getSalesPrice: () => '5000',
    isSales: () => true,
  },
  {
    postNo: 1,
    title: '게시글1',
    id: 'userName_1',
    price: '10000',
    salesPrice: '5000',
    salesYn: 'Y',
    salesPct: '50 %',
    tags: 'TEST',
    originName: 'aasaasdasdasd',

    getTags: () => ['test'],
    getPrice: () => '10000',
    getSalesPrice: () => '5000',
    isSales: () => true,
  },
  {
    postNo: 1,
    title: '게시글1',
    id: 'userName_1',
    price: '10000',
    salesPrice: '5000',
    salesYn: 'Y',
    salesPct: '50 %',
    tags: 'TEST',
    originName: 'aasaasdasdasd',

    getTags: () => ['test'],
    getPrice: () => '10000',
    getSalesPrice: () => '5000',
    isSales: () => true,
  },
  {
    postNo: 1,
    title: '게시글1',
    id: 'userName_1',
    price: '10000',
    salesPrice: '5000',
    salesYn: 'Y',
    salesPct: '50 %',
    tags: 'TEST,TEST2',
    originName: 'aasaasdasdasd',

    getTags: () => ['test'],
    getPrice: () => '10000',
    getSalesPrice: () => '5000',
    isSales: () => true,
  },
  {
    postNo: 1,
    title: '게시글1',
    id: 'userName_1',
    price: '10000',
    salesPrice: '5000',
    salesYn: 'Y',
    salesPct: '50 %',
    tags: 'TEST',
    originName: 'aasaasdasdasd',

    getTags: () => ['test'],
    getPrice: () => '10000',
    getSalesPrice: () => '5000',
    isSales: () => true,
  },
  {
    postNo: 1,
    title: '게시글1',
    id: 'userName_1',
    price: '10000',
    salesPrice: '5000',
    salesYn: 'Y',
    salesPct: '50 %',
    tags: 'TEST',
    originName: 'aasaasdasdasd',

    getTags: () => ['test'],
    getPrice: () => '10000',
    getSalesPrice: () => '5000',
    isSales: () => true,
  },
  {
    postNo: 1,
    title: '게시글1',
    id: 'userName_1',
    price: '10000',
    salesPrice: '5000',
    salesYn: 'Y',
    salesPct: '50 %',
    tags: 'TEST',
    originName: 'aasaasdasdasd',

    getTags: () => ['test'],
    getPrice: () => '10000',
    getSalesPrice: () => '5000',
    isSales: () => true,
  },
]
